name: focus_wave
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.7.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/rain.mp3
    - assets/audio/fire.mp3
    - assets/audio/cafe.mp3
    - assets/audio/wave.mp3
    - assets/audio/alert.mp3